#!/bin/bash

[[ -d $1 ]] || { echo "This is not a directory."; exit 1; }

function main()
{
  cd $1/

  local love_pkg_name=""

  love_pkg_name=${1%/}
  love_pkg_name=${love_pkg_name##*/}

  zip -9 -rv ${love_pkg_name}.love *
  mv -v ${love_pkg_name}.love ../
}

main $1

